/* Real logo files from public/skills: nothing stock. */
export const tools: { name: string; icon: string }[] = [
  { name: 'Python', icon: '/skills/Python-logo.png' },
  { name: 'C++', icon: '/skills/ISO_C++_Logo.svg.webp' },
  { name: 'JavaScript', icon: '/skills/javascript.png' },
  { name: 'TypeScript', icon: '/skills/typescript.png' },
  { name: 'React', icon: '/skills/react.png' },
  { name: 'Next.js', icon: '/skills/nextjs.png' },
  { name: 'Django', icon: '/skills/django.jpeg' },
  { name: 'FastAPI', icon: '/skills/fastapi.png' },
  { name: 'pandas', icon: '/skills/pandas.png' },
  { name: 'NumPy', icon: '/skills/numpy.png' },
  { name: 'scikit-learn', icon: '/skills/scikit learn.webp' },
  { name: 'PyTorch', icon: '/skills/pytorch.png' },
  { name: 'TensorFlow', icon: '/skills/Tensorflow_logo.svg.webp' },
  { name: 'XGBoost', icon: '/skills/66d8691e2943609aef09f8ee_xgboost.png' },
  { name: 'OpenCV', icon: '/skills/38-384674_opencv-logo-png-transparent-png.png' },
  { name: 'YOLO', icon: '/skills/yolo.jpg' },
  { name: 'Grad-CAM', icon: '/skills/gradcam.png' },
  { name: 'Neo4j', icon: '/skills/neo4j.png' },
  { name: 'MongoDB', icon: '/skills/mongodb-logo-png_seeklogo-481256.png' },
  { name: 'PostgreSQL', icon: '/skills/postgresql.png' },
  { name: 'MySQL', icon: '/skills/logo-mysql-mysql-logo-png-images-are-download-crazypng-21.png' },
  { name: 'Git', icon: '/skills/git.png' },
];
